# Generated by Django 3.1.1 on 2020-09-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
