# Generated by Django 3.0.7 on 2020-11-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_cmovil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='umovil',
            field=models.CharField(default='Homero', max_length=20),
        ),
    ]
