# Generated by Django 3.0.7 on 2020-11-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_personal_umovil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='umovil',
        ),
    ]
