# Generated by Django 3.0.7 on 2020-11-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20201103_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='nombre',
        ),
    ]
