# Generated by Django 3.0.7 on 2020-11-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='distancia',
            field=models.FloatField(default=0.0),
        ),
    ]
