# Generated by Django 3.0.7 on 2020-11-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_ruta_distancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
