# Generated by Django 3.0.7 on 2020-11-04 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_auto_20201104_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='fecha',
            field=models.DateField(default=datetime.date(2020, 11, 4)),
        ),
    ]
