# Generated by Django 3.0.7 on 2020-11-04 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_ruta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
