# Generated by Django 3.0.7 on 2020-11-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0005_auto_20201104_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='direcciones_ordenadas',
            field=models.CharField(default=' ', max_length=50000),
        ),
        migrations.AddField(
            model_name='ruta',
            name='link',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
