# Generated by Django 3.0.7 on 2020-11-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_auto_20201104_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='pacientes',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
