# Generated by Django 3.0.7 on 2020-11-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_ruta_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='pos_actual',
            field=models.IntegerField(default=0),
        ),
    ]
