# Generated by Django 3.0.7 on 2020-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0008_ruta_pos_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='mapa_sb',
            field=models.CharField(default='', max_length=200000),
        ),
    ]
