# Generated by Django 3.0.7 on 2020-11-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0009_ruta_mapa_sb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='mapa_sb',
            new_name='mapa',
        ),
    ]
