# Generated by Django 3.0.7 on 2020-11-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0010_auto_20201105_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='mapa',
        ),
    ]
