# Generated by Django 3.1.1 on 2020-09-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tutor', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('titulo', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=400)),
                ('estado', models.IntegerField(default=0)),
                ('respuesta', models.CharField(default='Sin Respuesta', max_length=400)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
