# Generated by Django 3.1.1 on 2020-09-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Llamar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=40)),
                ('texto_explicativo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tiempos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('tiempo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_paciente', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('equipo', models.CharField(default='Disponible', max_length=20)),
                ('episodio', models.IntegerField(default=0)),
            ],
        ),
    ]
