# Generated by Django 3.0.7 on 2020-11-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='apellido1',
            field=models.CharField(default='Sin asignar', max_length=30),
        ),
        migrations.AddField(
            model_name='visita',
            name='apellido2',
            field=models.CharField(default='Sin asignar', max_length=30),
        ),
        migrations.AddField(
            model_name='visita',
            name='comuna',
            field=models.CharField(default='Sin asignar', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='domicilio',
            field=models.CharField(default='Sin asignar', max_length=50),
        ),
        migrations.AddField(
            model_name='visita',
            name='nombre',
            field=models.CharField(default='Sin asignar', max_length=30),
        ),
        migrations.AddField(
            model_name='visita',
            name='num_domicilio',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='visita',
            name='rut',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
