# Generated by Django 3.0.7 on 2020-11-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0002_auto_20201104_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='nombre2',
            field=models.CharField(default='Sin asignar', max_length=30),
        ),
    ]
