# Generated by Django 3.0.7 on 2020-11-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0003_visita_nombre2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='nombre2',
        ),
    ]
