# Generated by Django 3.0.7 on 2020-11-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0006_auto_20201122_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='observaciones',
        ),
    ]
