# Generated by Django 3.0.7 on 2020-11-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0007_remove_visita_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='hora_inicio',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='hora_termino',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='observaciones',
            field=models.CharField(default=' ', max_length=30000),
        ),
    ]
