# Generated by Django 3.0.7 on 2020-11-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0008_auto_20201122_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='hora_termino',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
