# Generated by Django 3.1.1 on 2020-09-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_visita', models.IntegerField()),
                ('id_especialista', models.IntegerField()),
                ('id_paciente', models.IntegerField(default=0)),
                ('h_inicio', models.TimeField()),
                ('h_termino', models.TimeField(auto_now_add=True)),
                ('antecedentes', models.CharField(default='Vacio', max_length=400)),
                ('red_apoyo', models.CharField(default='Vacio', max_length=20)),
                ('indice_barthel', models.IntegerField(default=0)),
                ('escala_braden', models.IntegerField(default=0)),
                ('escala_norton', models.IntegerField(default=0)),
                ('detalle', models.CharField(default='Vacio', max_length=400)),
                ('evolucion', models.CharField(default='Vacio', max_length=400)),
                ('pendientes', models.CharField(default='Vacio', max_length=400)),
                ('comentarios', models.CharField(default='Vacio', max_length=400)),
                ('nota', models.IntegerField(default=0)),
                ('episodio', models.IntegerField(default=0)),
            ],
        ),
    ]
